const data = {
  productsData: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
      isFeatured: true,
    },
    {
      name: "adidas Slim",
      slug: "nike-slim",
      category: "Shirts",
      image: "/images/p2.png",
      price: 120,
      countInStock: 10,
      brand: "adidas",
      rating: 3.5,
      numReviews: 10,
      description: "high quality shirt",
      isFeatured: true,
    },
    {
      name: "adidas shirt",
      slug: "adidas-shirt",
      category: "Shirts",
      image: "/images/p3.png",
      price: 320,
      countInStock: 10,
      brand: "adidas",
      rating: 4.8,
      numReviews: 10,
      description: "high quality shirt",
      isFeatured: true,
    },
  ],
};

export default data;
